-- AlterTable
ALTER TABLE "Assessment" ADD COLUMN     "dietaryProfile" TEXT,
ADD COLUMN     "glpCommunication" TEXT,
ADD COLUMN     "learningModality" TEXT,
ADD COLUMN     "motorFatigue" TEXT,
ADD COLUMN     "readingProcessing" TEXT,
ADD COLUMN     "repetitiveComfortScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "routineDistress" TEXT,
ADD COLUMN     "socialEngagement" TEXT,
ADD COLUMN     "spatialConstructiveScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taskPersistenceScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transitionAdaptabilityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "patternLogicScore" SET DEFAULT 0,
ALTER COLUMN "patternLogicScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sensoryRegulationScore" SET DEFAULT 0,
ALTER COLUMN "sensoryRegulationScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "verbalExpressiveScore" SET DEFAULT 0,
ALTER COLUMN "verbalExpressiveScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fineMotorScore" SET DEFAULT 0,
ALTER COLUMN "fineMotorScore" SET DATA TYPE DOUBLE PRECISION;
