import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import Link from "next/link";
import ExportClientActions from "./ExportClientActions";

export default async function WeeklyExportPage(props: {
  params: Promise<{ id: string }>;
}) {
  const params = await props.params;
  const childId = params.id;

  const child = await prisma.child.findUnique({
    where: { id: childId },
    include: {
      oneYearPlan: true,
      weeklyCheckins: {
        where: {
          OR: [
            { aiInference: { not: null } },
            { isSurvivalMode: true }
          ]
        },
        orderBy: { weekNumber: "desc" },
        take: 4, 
      },
    },
  });

  if (!child || !child.oneYearPlan) notFound();

  const recentWeeks = child.weeklyCheckins;

  // Aggregate successful strategies
  const successfulStrategies = recentWeeks.flatMap(week => {
    if (week.isSurvivalMode) return [];
    const tasks = (week.weeklyTasks as any[]) || [];
    const completedTasksData = (week.tasksCompleted as any[]) || [];
    
    return completedTasksData
      .filter(tc => tc.completed)
      .map(tc => tasks[tc.taskIndex]?.task)
      .filter(Boolean);
  });

  return (
    <div className="max-w-4xl mx-auto p-8 bg-white min-h-screen border shadow-sm my-8 print:my-0 print:border-none print:shadow-none">
      
      {/* 🟢 THIS HANDLES THE BACK BUTTON AND PRINT BUTTON */}
      <ExportClientActions childId={childId} />

      {/* Clinical Header */}
      <div className="border-b-4 border-slate-900 pb-6 mb-8">
        <h1 className="text-3xl font-black text-slate-900 mb-2 uppercase tracking-tight">Clinical Progress Update</h1>
        <div className="grid grid-cols-2 gap-4 text-sm text-slate-700 font-medium">
          <div><span className="text-slate-500 mr-2">Patient:</span> {child.name}</div>
          <div><span className="text-slate-500 mr-2">Age:</span> {child.age ?? "N/A"}</div>
          <div><span className="text-slate-500 mr-2">Report Date:</span> {new Date().toLocaleDateString()}</div>
          <div><span className="text-slate-500 mr-2">Period:</span> Last {recentWeeks.length} Weeks</div>
        </div>
      </div>

      {/* Goal Section */}
      <div className="mb-10">
        <h2 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-3 border-b border-slate-200 pb-2">Current Home Focus</h2>
        <p className="text-lg text-slate-900 font-medium leading-relaxed bg-slate-50 p-5 rounded-xl border border-slate-100">
          "{child.oneYearPlan.publishedGoal}"
        </p>
      </div>

      {/* Strategies */}
      <div className="mb-10">
        <h2 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-3 border-b border-slate-200 pb-2">Successful Strategies</h2>
        {successfulStrategies.length > 0 ? (
          <ul className="list-disc pl-6 space-y-2 text-slate-800">
            {Array.from(new Set(successfulStrategies)).map((strategy, i) => (
              <li key={i}>{strategy}</li>
            ))}
          </ul>
        ) : (
          <p className="text-slate-500 italic">Focus was on baseline regulation this period.</p>
        )}
      </div>

      {/* Weekly Breakdown */}
      <div className="space-y-6">
        <h2 className="text-sm font-bold text-slate-500 uppercase tracking-widest border-b border-slate-200 pb-2">Chronological Log</h2>
        {recentWeeks.map((week) => (
          <div key={week.id} className="bg-white border border-slate-200 rounded-xl p-6 break-inside-avoid">
            <div className="flex justify-between items-center mb-4 border-b border-slate-100 pb-2">
              <h3 className="font-bold text-slate-900">Week {week.weekNumber}</h3>
              <span className="text-xs font-bold text-slate-500">
                {week.isSurvivalMode ? "Low Demand Mode" : `Score: ${week.progressScore?.toFixed(1) ?? "N/A"}/10`}
              </span>
            </div>
            <p className="text-sm text-slate-700">{week.parentObservations || "No specific observations logged."}</p>
          </div>
        ))}
      </div>

      <div className="mt-12 pt-6 border-t border-slate-200 text-center text-[10px] text-slate-400">
        Generated by SpecialCare by Medha Labs. For clinical collaboration only.
      </div>
    </div>
  );
}